In [2]:
import torch
from PIL import Image
import numpy as np

In [3]:
img = Image.open('lena.png')

bwimg = img.convert("L")
w,h =bwimg.size

print(w,h)

nimg = np.array(bwimg)

sobel_horizontal=[[-1, 0, 1],
                  [-2, 0, 2],
                  [-1, 0, 1]]

sobel_vertical=[[-1, -2, -1],
                [0, 0, 0],
                [1, 2, 1]]


def convolution(image,kernel,padding):
    iw,ih =image.shape
    kw,kh =kernel.shape

    if padding=='same':
        pad_h = kh//2
        pad_w = kw//2
    elif padding=='valid':
        pad_h=pad_w=0
    elif isinstance(padding,int):
        pad_h = pad_w = padding
    else:
        raise ValueError("Invalid padding option")
    
    #padding the image
    padded_image = np.pad(image,((pad_h,pad_h),(pad_w,pad_w)),mode='constant')

    #output size
    oh = ih if padding=='same' else ih - kh + 1
    ow = iw if padding=='same' else iw - kw + 1

    

        

440 440


In [4]:
a= np.array([[3,3,2,1,0],
    [0,0,1,3,1],
    [3,1,2,2,3],
    [2,0,0,2,2],
    [2,0,0,0,1]])

k = np.array([[0,1,2],
     [2,2,0],
     [0,1,2]])

ah,aw = a.shape
kh,kw = k.shape

#padding to preserve the size (i.e output size same as input)
pad_h=kh//2
pad_w=kw//2

a_padded = np.zeros((ah+2*pad_h, aw+2*pad_w))
a_padded[pad_h:pad_h+ah, pad_w:pad_w+aw] = a

# oh,ow =ah-kh+1,aw-kw+1
output = np.zeros((ah,aw))
for h in range(ah):
    for w in range(aw):
        region = a_padded[h:h+kh,w:w+kw]
        output[h,w] = np.sum(region*k)

print(output)

[[ 6. 14. 17. 11.  3.]
 [14. 12. 12. 17. 11.]
 [ 8. 10. 17. 19. 13.]
 [11.  9.  6. 14. 12.]
 [ 6.  4.  4.  6.  4.]]


In [5]:
print("Kernel:\n", k)
print("Input:\n", a)


Kernel:
 [[0 1 2]
 [2 2 0]
 [0 1 2]]
Input:
 [[3 3 2 1 0]
 [0 0 1 3 1]
 [3 1 2 2 3]
 [2 0 0 2 2]
 [2 0 0 0 1]]


In [6]:
import torch
import torch.nn.functional as F

# Input 2D array (image)
a = torch.tensor([[3, 3, 2, 1, 0],
                  [0, 0, 1, 3, 1],
                  [3, 1, 2, 2, 3],
                  [2, 0, 0, 2, 2],
                  [2, 0, 0, 0, 1]], dtype=torch.float32)

# Kernel
k = torch.tensor([[0, 1, 2],
                  [2, 2, 0],
                  [0, 1, 2]], dtype=torch.float32)

# Reshape for conv2d:
# a: (1, 1, H, W)
# k: (1, 1, kh, kw)
a = a.unsqueeze(0).unsqueeze(0)         # shape: (1, 1, 5, 5)
k = k.unsqueeze(0).unsqueeze(0)         # shape: (1, 1, 3, 3)

# Apply convolution with padding=1 (to preserve size)
output = F.conv2d(a, k, padding=1)

# Remove extra dimensions
print(output.squeeze())  # shape: (5, 5)


tensor([[ 6., 14., 17., 11.,  3.],
        [14., 12., 12., 17., 11.],
        [ 8., 10., 17., 19., 13.],
        [11.,  9.,  6., 14., 12.],
        [ 6.,  4.,  4.,  6.,  4.]])


In [44]:
vs = Image.open('profileimg2.jpg').convert('L')

In [45]:
a = np.array(vs)

print(a.shape)
k = np.array([[0,1,2],
     [2,2,0],
     [0,1,2]])

ah,aw = a.shape
kh,kw = k.shape

#padding to preserve the size (i.e output size same as input)
pad_h=kh//2
pad_w=kw//2

a_padded = np.zeros((ah+2*pad_h, aw+2*pad_w))
a_padded[pad_h:pad_h+ah, pad_w:pad_w+aw] = a

# oh,ow =ah-kh+1,aw-kw+1
output = np.zeros((ah,aw))
for h in range(ah):
    for w in range(aw):
        region = a_padded[h:h+kh,w:w+kw]
        output[h,w] = np.sum(region*k)

print(output)


(2305, 2305)
[[ 955. 1337. 1337. ... 1568. 1568. 1120.]
 [1528. 1910. 1910. ... 2240. 2240. 1344.]
 [1528. 1910. 1910. ... 2240. 2240. 1344.]
 ...
 [ 302.  389.  386. ... 2360. 2370. 1416.]
 [ 349.  452.  451. ... 2370. 2357. 1399.]
 [ 226.  330.  340. ... 1592. 1617. 1160.]]


In [46]:
# Normalize output to 0–255
output -= output.min()
output = output / output.max() * 255
output = output.astype(np.uint8)

# Convert to image and show
convvs = Image.fromarray(output)
convvs.show()

Convolution function

In [55]:
# Kernels
#edge detection
sobel_x = np.array([[-1, 0, 1],
                    [-2, 0, 2],
                    [-1, 0, 1]])

sobel_y = np.array([[-1, -2, -1],
                    [ 0,  0,  0],
                    [ 1,  2,  1]])

laplacian = np.array([[ 0, -1,  0],
                      [-1,  4, -1],
                      [ 0, -1,  0]])

#Blur Gaussian
gaussian = (1/16) * np.array([[1, 2, 1],
                              [2, 4, 2],
                              [1, 2, 1]])

box_blur = (1/9) * np.ones((3, 3))

emboss = np.array([[-2, -1, 0],
                   [-1,  1, 1],
                   [ 0,  1, 2]])

outline =10*np.array([[-1, -1, -1],
                    [-1,  8, -1],
                    [-1, -1, -1]])



In [56]:
def convolution(img, kernel):
    a=np.array(img)
    k=kernel
    ah,aw = a.shape
    kh,kw = k.shape

    #padding to preserve the size (i.e output size same as input)
    pad_h=kh//2
    pad_w=kw//2

    a_padded = np.zeros((ah+2*pad_h, aw+2*pad_w))
    a_padded[pad_h:pad_h+ah, pad_w:pad_w+aw] = a

    # oh,ow =ah-kh+1,aw-kw+1
    output = np.zeros((ah,aw))
    for h in range(ah):
        for w in range(aw):
            region = a_padded[h:h+kh,w:w+kw]
            output[h,w] = np.sum(region*k)

    # Normalize output to 0–255
    output -= output.min()
    output = output / output.max() * 255
    output = output.astype(np.uint8)

    # Convert to image and show
    convvs = Image.fromarray(output)
    convvs.show()

In [62]:
img = Image.open('profileimg2.jpg').convert('L') #converting to grayscale
convolution(img,sobel_y)

Convolution function with color images

In [63]:
def color_convolution(img, kernel):
    a = np.array(img)  # shape: (H, W, 3) for RGB
    k = kernel
    kh, kw = k.shape
    pad_h, pad_w = kh // 2, kw // 2

    if len(a.shape) == 2:  # Grayscale
        a = np.expand_dims(a, axis=2)

    h, w, c = a.shape
    output = np.zeros((h, w, c), dtype=np.float32)

    for ch in range(c):  # Process each channel separately
        channel = a[:, :, ch]
        padded = np.pad(channel, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)

        for i in range(h):
            for j in range(w):
                region = padded[i:i+kh, j:j+kw]
                output[i, j, ch] = np.sum(region * k)

    # Normalize the entire image
    output -= output.min()
    output = output / output.max() * 255
    output = output.astype(np.uint8)

    # Convert back to image and show
    conv_img = Image.fromarray(output)
    conv_img.show()

In [67]:
color_img = Image.open('profileimg2.jpg').convert('RGB')
color_convolution(color_img, sobel_x)